image: rossedlin/php-apache:8.1
pipelines:
  branches:
    '{master,youtube}':
      # Test
      - step:
          name: Test
          caches:
            - composer
          script:
            - composer install --prefer-dist --no-ansi --no-interaction --no-progress
            - php -r "file_exists('.env') || copy('.env.example', '.env');"
            - php artisan key:generate
            - vendor/bin/phpunit --coverage-text --colors=never --verbos
      # Deploy
      - step:
          name: Deploy
          deployment: production
          caches:
            - composer
          script:
            - ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/bitbucket/chat-laravel-pusher && git pull;'
            - ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/bitbucket/chat-laravel-pusher && /opt/alt/php81/usr/bin/php ~/composer.phar install --no-dev --prefer-dist --no-ansi --no-interaction --no-progress;'
