version: '3.3'

services:
   web:
     image: rossedlin/php-apache:8.1
     ports:
       - "80:80"
     volumes:
       - ./:/var/www

   build:
       image: rossedlin/nodejs:18
       volumes:
           - ./:/home/node/app
